import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../app/localization/app_localizations.dart';
import '../../../core/widgets/empty_state.dart';
import '../../../core/widgets/error_state.dart';
import '../../../core/widgets/loading_state.dart';
import '../../activity_logs/data/activity_repository.dart';
import '../../authentication/data/auth_repository.dart';
import '../../categories/data/category_repository.dart';
import '../../references/presentation/reference_detail_screen.dart';
import '../data/snippet_repository.dart';
import '../domain/snippet_model.dart';

class AddSnippetScreen extends ConsumerStatefulWidget {
  final String referenceId;

  const AddSnippetScreen({Key? key, required this.referenceId}) : super(key: key);

  @override
  ConsumerState<AddSnippetScreen> createState() => _AddSnippetScreenState();
}

class _AddSnippetScreenState extends ConsumerState<AddSnippetScreen> {
  final _formKey = GlobalKey<FormState>();
  
  final _titleController = TextEditingController();
  final _titleArController = TextEditingController();
  final _textController = TextEditingController();
  final _pageController = TextEditingController();
  final _sectionController = TextEditingController();
  final _keywordsController = TextEditingController();
  final _notesController = TextEditingController();

  String? _selectedCategoryId;
  bool _isSaving = false;

  @override
  void dispose() {
    _titleController.dispose();
    _titleArController.dispose();
    _textController.dispose();
    _pageController.dispose();
    _sectionController.dispose();
    _keywordsController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  void _submit() async {
    if (_formKey.currentState?.validate() ?? false) {
      if (_selectedCategoryId == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Please select a category'), backgroundColor: Colors.red),
        );
        return;
      }

      final user = ref.read(authRepositoryProvider).currentUser;
      if (user == null) return;

      setState(() {
        _isSaving = true;
      });

      // Parse keywords
      final List<String> tags = _keywordsController.text
          .split(',')
          .map((s) => s.trim().toLowerCase())
          .where((s) => s.isNotEmpty)
          .toList();

      final newSnippet = EvidenceSnippet(
        id: '', // Generated by repository/DB
        referenceId: widget.referenceId,
        title: _titleController.text.trim(),
        titleAr: _titleArController.text.trim().isEmpty ? null : _titleArController.text.trim(),
        evidenceText: _textController.text.trim(),
        pageNumber: _pageController.text.trim().isEmpty ? null : int.parse(_pageController.text.trim()),
        sectionName: _sectionController.text.trim().isEmpty ? null : _sectionController.text.trim(),
        categoryId: _selectedCategoryId,
        keywords: tags,
        notes: _notesController.text.trim().isEmpty ? null : _notesController.text.trim(),
        addedBy: user.id,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      try {
        final snippetRepo = ref.read(snippetRepositoryProvider);
        final activityRepo = ref.read(activityRepositoryProvider);

        final result = await snippetRepo.addSnippet(newSnippet);

        await activityRepo.logActivity(
          action: 'create_snippet',
          entityType: 'snippet',
          entityId: result.id,
          description: 'Added new snippet: "${result.title}" to reference ID ${widget.referenceId}.',
        );

        // Invalidate lists to trigger UI update
        ref.invalidate(snippetsListProvider(widget.referenceId));

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text(context.tr('addSnippetSuccess'))),
          );
          context.go('/references/${widget.referenceId}');
        }
      } catch (e) {
        setState(() {
          _isSaving = false;
        });
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text(e.toString()), backgroundColor: Colors.red),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final categoriesAsync = ref.watch(categoriesProvider);
    final refDetailsAsync = ref.watch(referenceDetailsProvider(widget.referenceId));

    return Scaffold(
      appBar: AppBar(
        title: Text(context.tr('addSnippet')),
      ),
      body: refDetailsAsync.when(
        loading: () => const LoadingState(),
        error: (err, stack) => ErrorState(message: err.toString()),
        data: (refModel) {
          if (refModel == null) {
            return const EmptyState(message: 'Reference parent not found');
          }

          final refTitle = context.isRTL && refModel.titleAr != null && refModel.titleAr!.isNotEmpty
              ? refModel.titleAr!
              : refModel.title;

          return categoriesAsync.when(
            loading: () => const LoadingState(),
            error: (err, stack) => ErrorState(message: err.toString()),
            data: (categories) {
              if (categories.isEmpty) {
                return const EmptyState(message: 'No categories available.');
              }

              if (_selectedCategoryId == null) {
                // Pre-populate with parent reference category if possible, or first category
                _selectedCategoryId = refModel.categoryId ?? categories.first.id;
              }

              return SingleChildScrollView(
                padding: const EdgeInsets.all(24.0),
                child: Center(
                  child: ConstrainedBox(
                    constraints: const BoxConstraints(maxWidth: 800),
                    child: Card(
                      child: Padding(
                        padding: const EdgeInsets.all(32.0),
                        child: Form(
                          key: _formKey,
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              // Reference Name Badge
                              Container(
                                padding: const EdgeInsets.all(12),
                                decoration: BoxDecoration(
                                  color: Theme.of(context).primaryColor.withOpacity(0.06),
                                  borderRadius: BorderRadius.circular(8),
                                ),
                                child: Row(
                                  children: [
                                    const Icon(Icons.bookmark_outline, size: 18),
                                    const SizedBox(width: 10),
                                    Expanded(
                                      child: Text(
                                        'Parent Reference: $refTitle',
                                        style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 13),
                                        maxLines: 1,
                                        overflow: TextOverflow.ellipsis,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              const SizedBox(height: 24),

                              // Snippet Title English
                              Text(context.tr('titleEn'), style: const TextStyle(fontWeight: FontWeight.bold)),
                              const SizedBox(height: 6),
                              TextFormField(
                                controller: _titleController,
                                decoration: const InputDecoration(hintText: 'e.g., Vaccination Guidelines for Household Contacts'),
                                validator: (value) => value == null || value.trim().isEmpty ? 'Required field' : null,
                              ),
                              const SizedBox(height: 20),

                              // Snippet Title Arabic
                              Text(context.tr('titleAr'), style: const TextStyle(fontWeight: FontWeight.bold)),
                              const SizedBox(height: 6),
                              TextFormField(
                                controller: _titleArController,
                                decoration: const InputDecoration(hintText: 'مثال: إرشادات التطعيم للمخالطين المنزليين'),
                              ),
                              const SizedBox(height: 20),

                              // Row: Section Name & Page Number
                              Row(
                                children: [
                                  Expanded(
                                    child: Column(
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Text(context.tr('sectionName'), style: const TextStyle(fontWeight: FontWeight.bold)),
                                        const SizedBox(height: 6),
                                        TextFormField(
                                          controller: _sectionController,
                                          decoration: const InputDecoration(hintText: 'e.g., Chapter 3 / Section B'),
                                        ),
                                      ],
                                    ),
                                  ),
                                  const SizedBox(width: 16),
                                  Expanded(
                                    child: Column(
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Text(context.tr('pageNumber'), style: const TextStyle(fontWeight: FontWeight.bold)),
                                        const SizedBox(height: 6),
                                        TextFormField(
                                          controller: _pageController,
                                          keyboardType: TextInputType.number,
                                          decoration: const InputDecoration(hintText: 'e.g., 42'),
                                          validator: (value) {
                                            if (value != null && value.trim().isNotEmpty) {
                                              if (int.tryParse(value) == null) {
                                                return 'Must be an integer';
                                              }
                                            }
                                            return null;
                                          },
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                              const SizedBox(height: 20),

                              // Category Dropdown
                              Text(context.tr('categories'), style: const TextStyle(fontWeight: FontWeight.bold)),
                              const SizedBox(height: 6),
                              DropdownButtonFormField<String>(
                                value: _selectedCategoryId,
                                items: categories.map((c) {
                                  final name = context.isRTL ? c.nameAr : c.nameEn;
                                  return DropdownMenuItem(value: c.id, child: Text(name));
                                }).toList(),
                                onChanged: (val) {
                                  if (val != null) {
                                    setState(() {
                                      _selectedCategoryId = val;
                                    });
                                  }
                                },
                              ),
                              const SizedBox(height: 20),

                              // Text (The evidence excerpt itself) - REQUIRED
                              Text(context.tr('evidenceText'), style: const TextStyle(fontWeight: FontWeight.bold)),
                              const SizedBox(height: 6),
                              TextFormField(
                                controller: _textController,
                                maxLines: 6,
                                decoration: const InputDecoration(
                                  hintText: 'Enter the exact verified text of the evidence here...',
                                ),
                                validator: (value) => value == null || value.trim().isEmpty ? 'Required field' : null,
                              ),
                              const SizedBox(height: 20),

                              // Keywords
                              Text(context.tr('keywords'), style: const TextStyle(fontWeight: FontWeight.bold)),
                              const SizedBox(height: 6),
                              TextFormField(
                                controller: _keywordsController,
                                decoration: const InputDecoration(hintText: 'e.g., vaccine, dosing, pediatric, contacts'),
                              ),
                              const SizedBox(height: 20),

                              // Notes
                              Text(context.tr('notes'), style: const TextStyle(fontWeight: FontWeight.bold)),
                              const SizedBox(height: 6),
                              TextFormField(
                                controller: _notesController,
                                maxLines: 3,
                                decoration: const InputDecoration(hintText: 'Any extra internal notes or flags for editors...'),
                              ),
                              const SizedBox(height: 32),

                              // Submit Actions
                              Row(
                                mainAxisAlignment: MainAxisAlignment.end,
                                children: [
                                  TextButton(
                                    onPressed: _isSaving ? null : () => context.pop(),
                                    child: Text(context.tr('cancel')),
                                  ),
                                  const SizedBox(width: 16),
                                  ElevatedButton(
                                    onPressed: _isSaving ? null : _submit,
                                    child: _isSaving
                                        ? const SizedBox(
                                            height: 20,
                                            width: 20,
                                            child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                                          )
                                        : Text(context.tr('save')),
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              );
            },
          );
        },
      ),
    );
  }
}
